[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "calculator"
version = "0.1.0"
description = "A tiny calculator package with CLI"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
calculator = "calculator.cli:main"
