name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.10, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -r requirements-dev.txt

      - name: Run formatter check (black)
        run: |
          python -m pip install black
          python -m black --check .

      - name: Run linter (flake8)
        run: |
          python -m pip install flake8
          python -m flake8

      - name: Run tests
        run: |
          python -m pytest -q
