name: Deploy web to user site repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy web/ to user site repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_REPO_TOKEN }}
          publish_branch: main
          publish_dir: ./web
          destination_repo: Rylan-johnson-dev67/python-calculator.github.io
