name: Deploy Pages

on:
  push:
    branches: [ main, master ]
  # Allow manual dispatch from Actions UI
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for optional build steps)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: web

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
